export enum Tags {
  burgers = 'burgers',
  sushi = 'sushi',
  pizza = 'pizza',
  wok = 'wok',
  paste = 'paste',
  soups = 'soups',
  breakfasts = 'breakfasts',
  dinner = 'dinner',
  gruzia = 'gruzia',
  italy = 'italy',
  russian = 'russian',
  uzbek = 'uzbek',
  asia = 'asia',
  japan = 'japan',
  china = 'china',
  coffee = 'coffee',
  dessert = 'dessert',
  bakery = 'bakery',
  shashlik = 'shashlik',
  shawurma = 'shawurma',
  steaks = 'steaks',
  sandwiches = 'sandwiches',
  seafood = 'seafood',
  healthy = 'healthy',
  europe = 'europe',
  fastfood = 'fastfood',
  east = 'east',
  cavcaz = 'cavcaz',
  childrens = 'childrens',
}

export const TagsArray = [
  Tags.burgers,
  Tags.sushi,
  Tags.pizza,
  Tags.wok,
  Tags.paste,
  Tags.soups,
  Tags.breakfasts,
  Tags.dinner,
  Tags.gruzia,
  Tags.italy,
  Tags.russian,
  Tags.uzbek,
  Tags.asia,
  Tags.japan,
  Tags.china,
  Tags.coffee,
  Tags.dessert,
  Tags.bakery,
  Tags.shashlik,
  Tags.shawurma,
  Tags.steaks,
  Tags.sandwiches,
  Tags.seafood,
  Tags.healthy,
  Tags.europe,
  Tags.fastfood,
  Tags.east,
  Tags.cavcaz,
  Tags.childrens,
];
